### PR TITLE
Sprite inherited from cc.Sprite should invoke "cc.associateWithNative( this, cc.Sprite );" in constructor.

### PR DESCRIPTION
**Pull request by dumganhar**
Also Updated Presentation.js.

### CODE REVIEW

**Comment by dumganhar** [comment]
Hey Riq,
I notice some differences of the implementations in CCParticleFireworks(or other classes in CCParticleExamples) between cocos2d-iphone and cocos2d-x.
In initWithTotalParticles function, cocos2d-x and cocos2d-html5 will not set a default texture( fire.png ) to particle system.
We don't want to bring resources to engine.
So if not invoking setTexture after cc.ParticleXXX.create(), app will crash at ccGLBindTexture2D( m_pTexture->getName() ); since m_pTexture is NULL.

**Comment by ricardoquesada** [comment]
argh...
I don't like your the approach that you took.
If you create an object like: `cc.ParticleFire()`, either it should fail (because "fire.png" is not present), or create a valid object.

The alternative is to support a optional parameter:
`
cc.ParticleFire("fire.png");
`

**Comment by dumganhar** [comment]
Agree!
What do you think about that we put the memory data of "fire.png" into one head file?
When using <code>cc.ParticleFire.create();</code>, we read the data directly rather than read the file.
This can make sure the texture exists. And user doesn't need to remember to place the <code>fire.png</code> resource.

James

**Comment by ricardoquesada** [comment]
That sounds even better :)

**Comment by dumganhar** [comment]
I commited a PR at https://github.com/cocos2d/cocos2d-x/pull/1560.
And the  header file for fire.png is https://github.com/dumganhar/cocos2d-x/blob/174ad614fea13036a8a472120473ea0a327b2813/cocos2dx/particle_nodes/firePngData.h

**Pull request merged**
