### PR TITLE
changed deviceType to platform

### PR DESCRIPTION
**Pull request by Wu-Hao**

### CODE REVIEW

**Comment by ricardoquesada** [comment]
I think I sent a pull request with that change also... strange.

**Comment by linshun** [comment]
You sent a pull request for cocos2d-html5 engine. Hao fixed the Tests.

**Comment by ricardoquesada** [comment]
Perhaps I forgot to send you the PR... I don't know... here are my changes:
https://github.com/ricardoquesada/cocos2d-js-tests/commit/f1942cb761c6922fff21168c345e532975136ae4

**Comment by linshun** [comment]
I have checked the history, you sent it 5 days ago. 
However, github shows me that the files has different and need to be merged.
It is so strange.

**Pull request merged**
