### PR TITLE
adds Chipmunk test

### PR DESCRIPTION
**Pull request by ricardoquesada**
Adds Chipmunk test to the collection of tests.
For the moment it only works on cocos2d-iphone JSB.
JSB + cocos2d-x coming soon.

### CODE REVIEW

**Comment by linshun** [comment]
Thank you, Riq. I would like to add chipmunk-js in cocos2d-html5. I will add it soon.

**Comment by ricardoquesada** [comment]
That would be great! Thanks.

**Comment by linshun** [comment]
Riq，could you please update this pull request to use "extend" but no "goog" ? It can not run with Cocos2d-html5 now.

**Comment by ricardoquesada** [comment]
@linshun 
Although cocos2d-html5 uses "extend" instead of Google Closure, it is a good idea to have some samples that show how to use "Google Closure inheritance with cocos2d-html5.
At work, we are promoting "google closure inheritance" instead of "extend" since it is way faster.

**Pull request merged**
