### PR TITLE
New label ttf test

### PR DESCRIPTION
**Pull request by carlomorgantinizynga**
New JS test for CCLabeTTF + shadow + stroke

### CODE REVIEW

**Comment by linshun** [comment]
Hi @carlomorgantinizynga, could you please remove "Published files" from the PR?

**Comment by dumganhar** [comment]
It seems that this PR isn't based on cocos2d/cocos2d-js-tests .

**Comment by linshun** [comment]
Agree, looks like base on cocos2d-js-tests of cocos2d-x repo.

**Comment by carlomorgantinizynga** [comment]
I'm trying to understand why this is not based on  cocos2d/cocos2d-js-tests...fixing it ASAP. Sorry about that

**Pull request closed without merging**
